default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  url: "postgresql://zach:churchilllibdev@localhost:3432/churchilllib"

test:
  <<: *default
  url: "postgresql://zach:churchilllibtest@localhost:4432/churchilllib"

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
